language: php
php:
  - 7.0
  - 7.1

install:
  - travis_retry composer self-update
  - travis_retry composer --version
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - php vendor/bin/phpunit
